### ISSUE TITLE
Can run `make run-savant`

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [insight-platform/SavantPyTorchComparison#3]
Hi, when I try to run `make run-savant`, I get error
```
docker run --rm --gpus=all \
        -e MODEL_PATH=/cache/models/yolov8_pipeline \
        -v `pwd`/src/savant:/opt/savant/samples/yolov8_pipeline \
        -v `pwd`/data:/data:ro \
        -v `pwd`/cache:/cache \
        ghcr.io/insight-platform/savant-deepstream:latest samples/yolov8_pipeline/module_perf.yml
 INFO  insight::savant::config::module_config > Configuring module "yolov8_pipeline"...
 INFO  insight::savant::config::module_config > Getting schema/configurator for uridecodebin
 INFO  insight::savant::config::module_config > Getting schema/configurator for devnull_sink
 INFO  insight::savant::config::module_config > Getting schema/configurator for nvinfer
 INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@detector:v1(name=yolov8m): Path to the model files has been set to "/cache/models/yolov8_pipeline/yolov8m".
 INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@detector:v1(name=yolov8m): Model engine file has been set to "yolov8m.onnx_b1_gpu0_fp16.engine".
 INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@detector:v1(name=yolov8m): Model object labels have been loaded from "/cache/models/yolov8_pipeline/yolov8m/labels.txt".
 INFO  insight::savant::deepstream::nvinfer::element_config > Element nvinfer@detector:v1(name=yolov8m): Resulting configuration file "/cache/models/yolov8_pipeline/yolov8m/yolov8m_config_savant.txt" has been saved.
 INFO  insight::savant::config::module_config               > Pipeline batch size is set to 1.
 INFO  insight::savant::config::module_config               > Module configuration is complete.

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:47.793: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpeg2enc.so': libmpeg2encpp-2.1.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:47.813: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpeg2dec.so': libmpeg2.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:48.399: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_preprocess.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_preprocess.so: undefined symbol: cuGraphicsEGLRegisterImage

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:50.002: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_ucx.so': libucs.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:50.019: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:50.037: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_infer.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_infer.so: undefined symbol: cuGraphicsEGLRegisterImage

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:50.058: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:38): GStreamer-WARNING **: 04:25:50.071: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_deepstream_bins.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_infer.so: undefined symbol: cuGraphicsEGLRegisterImage
 INFO  insight::savant::deepstream::utils::pipeline         > No tracing provider specified. Using noop tracer.
 INFO  insight::savant::yolov8_pipeline                     > Pipeline frame processing parameters: {'width': 1280, 'height': 720, 'batch-size': 1, 'batched-push-timeout': 40000, 'live-source': False, 'interpolation-method': 6, 'drop-pipeline-eos': False, 'nvbuf-memory-type': 3}.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/savant/entrypoint/__main__.py", line 43, in <module>
    main(args.config)
  File "/usr/local/lib/python3.8/dist-packages/savant/entrypoint/main.py", line 78, in main
    pipeline = NvDsPipeline(
  File "/usr/local/lib/python3.8/dist-packages/savant/deepstream/pipeline.py", line 182, in __init__
    super().__init__(name, pipeline_cfg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/pipeline.py", line 60, in __init__
    self.add_element(item, element_idx=i)
  File "/usr/local/lib/python3.8/dist-packages/savant/deepstream/pipeline.py", line 203, in add_element
    gst_element = super().add_element(
  File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/pipeline.py", line 89, in add_element
    gst_element = self._element_factory.create(element)
  File "/usr/local/lib/python3.8/dist-packages/savant/deepstream/element_factory.py", line 33, in create
    return super().create(element)
  File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/element_factory.py", line 32, in create
    return self.create_model_element(element)
  File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/element_factory.py", line 84, in create_model_element
    return GstElementFactory.create_element(element)
  File "/usr/local/lib/python3.8/dist-packages/savant/gstreamer/element_factory.py", line 51, in create_element
    raise CreateElementException(f'Unable to create element {element}.')
savant.gstreamer.element_factory.CreateElementException: Unable to create element ModelElement(element='nvinfer', element_type='detector', version='v1', name='yolov8m', properties={'config-file-path': '/cache/models/yolov8_pipeline/yolov8m/yolov8m_config_savant.txt'}, model=NvInferDetector(local_path='/cache/models/yolov8_pipeline/yolov8m', remote=None, model_file='yolov8m.onnx', batch_size=1, precision=<ModelPrecision.FP16: 2>, input=NvInferModelInput(object='auto.frame', layer_name=None, shape=[3, 640, 640], maintain_aspect_ratio=True, scale_factor=0.003921569790691137, offsets=[0.0, 0.0, 0.0], color_format=<ModelColorFormat.RGB: 0>, preprocess_object_meta=None, preprocess_object_image=None, object_min_width=None, object_min_height=None, object_max_width=None, object_max_height=None), output=NvInferObjectModelOutput(layer_names=['output0'], converter=PyFunc(module='samples.yolov8_pipeline.converter', class_name='TensorToBBoxConverter', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5, 'top_k': 300}, dev_mode=False), objects=[NvInferObjectModelOutputObject(class_id=0, label='person', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=1, label='bicycle', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=2, label='car', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=3, label='motorcycle', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=4, label='airplane', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=5, label='bus', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=6, label='train', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=7, label='truck', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=8, label='boat', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=9, label='traffic light', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=10, label='fire hydrant', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=11, label='stop sign', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=12, label='parking meter', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=13, label='bench', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=14, label='bird', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=15, label='cat', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=16, label='dog', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=17, label='horse', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=18, label='sheep', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=19, label='cow', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=20, label='elephant', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=21, label='bear', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=22, label='zebra', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=23, label='giraffe', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=24, label='backpack', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=25, label='umbrella', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=26, label='handbag', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=27, label='tie', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=28, label='suitcase', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=29, label='frisbee', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=30, label='skis', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=31, label='snowboard', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=32, label='sports ball', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=33, label='kite', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=34, label='baseball bat', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=35, label='baseball glove', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=36, label='skateboard', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=37, label='surfboard', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=38, label='tennis racket', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=39, label='bottle', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=40, label='wine glass', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=41, label='cup', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=42, label='fork', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=43, label='knife', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=44, label='spoon', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=45, label='bowl', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=46, label='banana', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=47, label='apple', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=48, label='sandwich', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=49, label='orange', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=50, label='broccoli', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=51, label='carrot', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=52, label='hot dog', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=53, label='pizza', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=54, label='donut', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=55, label='cake', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=56, label='chair', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=57, label='couch', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=58, label='potted plant', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=59, label='bed', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=60, label='dining table', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=61, label='toilet', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=62, label='tv', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=63, label='laptop', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=64, label='mouse', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=65, label='remote', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=66, label='keyboard', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=67, label='cell phone', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=68, label='microwave', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=69, label='oven', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=70, label='toaster', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=71, label='sink', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=72, label='refrigerator', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=73, label='book', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=74, label='clock', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=75, label='vase', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=76, label='scissors', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=77, label='teddy bear', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=78, label='hair drier', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False)), NvInferObjectModelOutputObject(class_id=79, label='toothbrush', selector=PyFunc(module='savant.selector.detector', class_name='BBoxSelector', kwargs={'confidence_threshold': 0.5, 'nms_iou_threshold': 0.5}, dev_mode=False))], num_detected_classes=80), format=<NvInferModelFormat.ONNX: 2>, config_file=None, int8_calib_file=None, engine_file='yolov8m.onnx_b1_gpu0_fp16.engine', proto_file=None, custom_config_file=None, mean_file=None, label_file='labels.txt', tlt_model_key=None, gpu_id=0, interval=0, workspace_size=6144, custom_lib_path=None, engine_create_func_name=None, parse_bbox_func_name=None)).
make: *** [Makefile:22: run-savant] Error 1
```

What caused this error and how can i fix it ?

**Comment by bwsw** [comment]
Hello, please check the requirements according to the docs: 
https://docs.savant-ai.io/v0.2.9/getting_started/0_configure_prod_env.html

If you are under WSL, we cannot help - WSL is not supported.
